model:
  model_name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  model_max_length: 8192
  torch_dtype_str: "bfloat16"
  trust_remote_code: true
  chat_template: "llama3-instruct"

data:
  train:
    datasets:
      - dataset_name: "text_sft"
        dataset_path: "/Users/aniruddhanramesh/dev/personal/summarization/MIMIC-IV-BHC/mimic-iv-bhc.jsonl"
    stream: false

training:
  output_dir: "/Users/aniruddhanramesh/dev/personal/summarization/MIMIC-IV-BHC/model"
  trainer_type: "TRL_SFT"
  use_peft: true

  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  num_train_epochs: 1
  logging_steps: 10
  save_steps: 100
  enable_wandb: false

peft:
  q_lora: true
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_quant_storage: "bfloat16"
  bnb_4bit_compute_dtype: "bfloat16"
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  lora_target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
